name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _/apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: _/apps/web/package.json
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
      - run: npm run build
